version: '3.5'

services:

  project:
    build:
      context: .
    volumes:
      - static:/app/static/
      - media:/app/media/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:8000
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project

volumes:
  static:
  media:
