services:

  project:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - static:/project/static/

  nginx:
    image: nginx:1.29
    ports:
      - 80:80
    volumes:
      - static:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project

volumes:
  static:
