# Generated by Django 5.0.3 on 2024-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи'
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name='Отчество'
            ),
        ),
    ]
