# Generated by Django 5.0.3 on 2024-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_role_alter_report_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
