# Generated by Django 5.0.3 on 2024-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_role_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
